import createFetchClient from 'openapi-fetch'
import createClient from 'openapi-react-query'

// generated by openapi-typescript
import { CONFIG } from '@/shared/model/config'

import { useSession } from '../model/session'

import { ApiPaths, ApiSchemas } from './schema'

export const fetchClient = createFetchClient<ApiPaths>({
  baseUrl: CONFIG.API_BASE_URL
})
export const rqClient = createClient(fetchClient)

fetchClient.use({
  async onRequest({ request }) {
    const token = useSession.getState().refreshToken()

    if (token) {
      request.headers.set('Autharization', `Bearer ${token}`)
    } else {
      return new Response(
        JSON.stringify({
          code: 'NOT_AUTHORIZED',
          message: 'You are not authorized to access'
        } as ApiSchemas['Error']),
        {
          status: 401,
          headers: {
            'Content-Type': 'application/json'
          }
        }
      )
    }
  }
})
