# переделать под продуктовые карточки

schemas:
  Product:
    type: object
    required:
      - id
      - title
      - price
      - image
      - description
      - category
      - createdAt
      - updatedAt
    properties:
      id:
        type: string
      title:
        type: string
      price:
        type: string
      image:
        type: string
        format: uri
      description:
        type: string
      category:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
  ProductsList:
    type: object
    required:
      - list
    properties:
      list:
        type: array
        items:
          $ref: '#/schemas/Product'

getAllProducts:
  summary: Get all products
  parameters:
    - name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 10
    - name: sort
      in: query
      required: false
      schema:
        type: string
        enum:
          - createdAt
          - updatedAt
          - title
  responses:
    '200':
      description: List of products
      content:
        application/json:
          schema:
            $ref: '#/schemas/ProductsList'
    '401':
      $ref: '../shared/responses.yaml#/UnauthorizedError'
